### PR TITLE
Fixing No ssidis returned

### PR DESCRIPTION
**Pull request by nniehoff**
Fixes: #90

### CODE REVIEW

**Review by chadell — APPROVED** [review]
LGTM

**Review by chadell — APPROVED** [review]

**Comment by ubajze** [comment]
@nniehoff @chadell @scetron 

I am not sure that this solves the issue completely. I think it just postpones the problem.
The `wireless` function calls one of two functions later in code:
https://github.com/nautobot/nautobot-plugin-chatops-ipfabric/blob/8bfe409d84db5a0fd34c74c72a4ce10a41929c20/nautobot_chatops_ipfabric/worker.py#L718-L719

There we have two similar lines as before:
https://github.com/nautobot/nautobot-plugin-chatops-ipfabric/blob/8bfe409d84db5a0fd34c74c72a4ce10a41929c20/nautobot_chatops_ipfabric/worker.py#L725

https://github.com/nautobot/nautobot-plugin-chatops-ipfabric/blob/8bfe409d84db5a0fd34c74c72a4ce10a41929c20/nautobot_chatops_ipfabric/worker.py#L781-L784

I am pretty sure we can update the first line similarly.

The second needs a different fix.
The original problem comes because the `wlanSsid` entry is None.

```
>>> print(json.dumps(rj, indent=4))
[
    {
        "wlanSsid": null,                <------------------ This
        "siteName": "HWLAB"
    },
    {
        "wlanSsid": "ipf-lab-aruba-wlc620",
        "siteName": "HWLAB"
    },
```

I am not sure how to test this properly in our lab.

**Comment by ubajze** [comment]
I added some updates, but I am not sure if we can test that in our environment. I checked and we don't have any radio without the SSID in our IPFabric snapshot.

**Review by pke11y — APPROVED** [review]
All good

**Pull request merged**
